services:

  postgres:
    image: postgres:16-bullseye
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - pulsar
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data

  pulsar:
    image: apachepulsar/pulsar:3.2.3
    container_name: pulsar
    command: >
      bin/pulsar standalone
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "bin/pulsar-admin brokers healthcheck || exit 1" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - pulsar
    ports:
      - "6650:6650"
      - "8080:8080"
    restart: always
    volumes:
      - ./pulsar-data:/pulsar/data

  pulsar-manager:
    image: apachepulsar/pulsar-manager:latest
    container_name: pulsar-manager
    depends_on:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    networks:
      - pulsar
    ports:
      - "9527:9527"
      - "7750:7750"
#    volumes:
#      - ./pulsar-manager/bin:/usr/local/bin

  init:
    image: appropriate/curl
    container_name: init
    depends_on:
      - pulsar-manager
    entrypoint: ["sh", "/init.sh"]
    networks:
      - pulsar
    volumes:
      - ./init/set-pulsar-manager-credential.sh:/init.sh

  debezium-server:
    image: debezium/server:2.7
    container_name: debezium-server
    environment:
      DEBEZIUM_SINK_TYPE: pulsar
      DEBEZIUM_SOURCE_CONNECTOR_CLASS: io.debezium.connector.postgresql.PostgresConnector
      DEBEZIUM_SOURCE_OFFSET_STORAGE_FILE_FILENAME: data/offsets.dat
      DEBEZIUM_SOURCE_OFFSET_FLUSH_INTERVAL_MS: 0
      DEBEZIUM_SOURCE_DATABASE_HOSTNAME: postgres
      DEBEZIUM_SOURCE_DATABASE_PORT: 5432
      DEBEZIUM_SOURCE_DATABASE_USER: myuser
      DEBEZIUM_SOURCE_DATABASE_PASSWORD: mypassword
      DEBEZIUM_SOURCE_DATABASE_DBNAME: mydatabase
      DEBEZIUM_SOURCE_DATABASE_SERVER_NAME: myserver
      DEBEZIUM_SOURCE_TOPIC_PREFIX: bizevents
      DEBEZIUM_SOURCE_PLUGIN_NAME: pgoutput
      QUARKUS_LOG_CONSOLE_JSON: false
      QUARKUS_LOG_CATEGORY__ORG_MY__LEVEL: DEBUG
    depends_on:
      pulsar:
        condition: service_healthy
    networks:
      - pulsar
    ports:
      - "8083:8080" # Expose Debezium Server port if needed for monitoring or REST API access
    volumes:
      - ./debezium/data:/debezium/data
      - ./debezium/conf:/debezium/conf

networks:
  pulsar:
    driver: bridge
